# Autogenerated wrapper script for NOMAD_jll for aarch64-apple-darwin
export libnomadAlgos, libnomadCInterface, libnomadEval, libnomadUtils, libsgtelib, nomad

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("NOMAD")
JLLWrappers.@declare_library_product(libnomadAlgos, "@rpath/libnomadAlgos.dylib")
JLLWrappers.@declare_library_product(libnomadCInterface, "@rpath/libnomadCInterface.dylib")
JLLWrappers.@declare_library_product(libnomadEval, "@rpath/libnomadEval.dylib")
JLLWrappers.@declare_library_product(libnomadUtils, "@rpath/libnomadUtils.dylib")
JLLWrappers.@declare_library_product(libsgtelib, "@rpath/libsgtelib.dylib")
JLLWrappers.@declare_executable_product(nomad)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libnomadAlgos,
        "lib/libnomadAlgos.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libnomadCInterface,
        "lib/libnomadCInterface.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libnomadEval,
        "lib/libnomadEval.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libnomadUtils,
        "lib/libnomadUtils.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libsgtelib,
        "lib/libsgtelib.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        nomad,
        "bin/nomad",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
